blank_issues_enabled: false
contact_links:
  - name: Feature Requests, Questions, and Chitchat
    url: https://github.com/hbjydev/harm/discussions
    about: Please ask and answer questions here instead of raising issues. :)
