/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const InitLazyImport = createFileRoute('/init')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const InitLazyRoute = InitLazyImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/init.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/init': typeof InitLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/init': typeof InitLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/init': typeof InitLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/init'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/init'
  id: '__root__' | '/' | '/init'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  InitLazyRoute: typeof InitLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  InitLazyRoute: InitLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/init"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/init": {
      "filePath": "init.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
